import turtle
turtle.setup(800,600)
window=turtle.Screen()
window.title("My bad")
tr=turtle.Turtle()
tr.hideturtle()
tr.forward(100)
tr.left(90)
tr.forward(100)
tr.left(90)
tr.forward(100)
tr.left(90)
tr.forward(100)
tr.exitonclicl()
